### PR TITLE
Fix to add Rate Limit Plugin with Redis Policy

### LINKED ISSUE #104: Consumer Rate Limiting by Redis not working
Setting up rate limiting by Redis requires the plugin to be setup with Redis credentials.  The Gateway Administration (gwa) API has these Redis credentials and therefore should be used to update the Consumer plugins rather than the Portal.  Perhaps any Consumer-related gateway changes should be moved to the gwa-api for consistency.

### PR DESCRIPTION
**Pull request by NithinKuruba**
Fixes #104

### CODE REVIEW

File: src/services/kong/consumer-service.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ const logger = Logger('kong');
 
 export class KongConsumerService {
   private kongUrl: string;
+  private gwaUrl: string = process.env.GWA_API_URL;
```
Comment (ikethecoder) [inline src/services/kong/consumer-service.ts:42]: Can you make consistent the setting of the values for`kongUrl` and `gwaUrl`?  They both are set from environment variables.  I prefer constructor injection, but either way, approach should be same.

**Review by ikethecoder — CHANGES_REQUESTED** [review]

File: src/services/kong/consumer-service.ts (hunk 1 above)
Comment (NithinKuruba) [reply src/services/kong/consumer-service.ts]: @ikethecoder Yup, I like the idea of constructor injection. Made the changes.

**Review by ikethecoder — APPROVED** [review]
