### PR TITLE
Signed JWT and Client Credential Changes

### LINKED ISSUE #101: Collect JWKS URL when requesting access
Screen Shot 2021-08-06 at 10 47 59 AM

**Setting the client authenticator options for Signed JWT:**

### LINKED ISSUE #108: Private key not loaded correctly into Keycloak

### LINKED ISSUE #137: Client is enabled even if approval request is failed and default scopes are removed from Keycloak
# API Services Portal Issue

API gateway deletes the default scopes from Keycloak

### ENV

- [ ] `DEV`
- [x ] `TEST`
- [ ] `PROD`

### TESTCASE
Same issuer as mentioned in https://github.com/bcgov/api-services-portal/issues/136

Process: Developer requesting for API
1. Client is created with default scopes
default_client_scopes

Process: Approver approving the request
Q 1: Request approval failed when approver selected the available scope
selected-scope-approval-failed

Q 2: Client enabled even if approval failed
approval-failed-but-client-enabled

Q 3:  request approved when only empty 'Roles' is selected but this lead to removal of default scopes for client
selected-blank-role-request-approved

default scopes are removed 
default-scopes-removed-after-apporval

-

### EXPECTED

1. Assign selected scope to the client with default scopes
2. Client not enabled when approval process is failed

-

### ACTUAL
1 Removes the default scopes
2 Does not assign the selected scope
3 Approval request is failed (https://github.com/bcgov/api-services-portal/issues/136)
4 Client is enabled even if approval is failed
-

### LINKED ISSUE #150: Reformat Client ID for OAuth2 Client Registration
The Client ID has the format: APP_ID-API_ID.  There is a request to flip those to API_ID-APP_ID to simplify searching in the Identity Provider.

We could make this as a configurable option in the Authorization Profile (CredentialIssuer) but considering there is no reason or requirement from other teams to keep it as APP_ID-API_ID, we will keep the solution simple and apply it globally for new client IDs that are created.

### LINKED ISSUE #165: Feature branch deployments fails to manage namespaces
The Product and Environment details need to be setup

### PR DESCRIPTION
**Pull request by ikethecoder**
Fixes #137 
Fixes #108 
Closes #101 
Closes #150 

There are also CI/CD Pipeline changes to seed feature branch deployments with the Gateway API Product Environment configuration so that features such as Namespace Management will work.  Fixes #165

### CODE REVIEW

File: src/nextapp/pages/devportal/requests/new/[id].tsx [hunk 1]
```diff
@@ -235,6 +243,21 @@ const NewRequestsPage: React.FC<
...
+              <Box pt={4}>
+                <FormControl>
+                  <FormLabel>
+                    JWKS URL of Public Keys for Signed JWT Authentication
+                  </FormLabel>
+                  <Input
+                    placeholder="https://"
+                    name="jwksUrl"
+                    variant="bc-input"
+                    defaultValue={''}
```
Comment (Jonesy) [inline src/nextapp/pages/devportal/requests/new/[id].tsx:256]: Nit-picky: just make this a `defaultValue=""`, no need to use the curly braces for an empty string.

File: src/nextapp/pages/devportal/requests/new/[id].tsx [hunk 2]
```diff
@@ -235,6 +243,21 @@ const NewRequestsPage: React.FC<
                 }))}
               value={environment}
             />
+            {clientAuthenticator == 'client-jwt-jwks-url' && (
```
Comment (Jonesy) [inline src/nextapp/pages/devportal/requests/new/[id].tsx:246]: Nit picky for consistency/best practice; use the `===` operator here.
