### PR TITLE
Fix backfilling of datasets in edit dialog

### LINKED ISSUE #41: Product edit dialog not backfilling datasets
Editing a product doesn't always have the current dataset selected.

### PR DESCRIPTION
**Pull request by Jonesy**
Fixes issue where previously set datasets were not being backfilled into the product edit form.

Fixes #41

### CODE REVIEW

File: src/nextapp/components/products-list/dataset-input.tsx [hunk 1]
```diff
@@ -108,7 +109,7 @@ const DatasetInput: React.FC<DatasetInputProps> = ({ value }) => {
                 {isOpen &&
                   isSuccess &&
                   data.allDatasets
-                    .filter((d) => !inputValue || d.title.includes(inputValue))
+                    .filter((d) => !inputValue || d.name.includes(inputValue))
```
Comment (Jonesy) [inline src/nextapp/components/products-list/dataset-input.tsx:112]: Search by `title`

**Review by ikethecoder — APPROVED** [review]
